### ISSUE TITLE
TIDAL HiFi volume control is erratic, overrides EarTrumpet

### ISSUE THREAD

**Issue by brian6932** [File-New-Project/EarTrumpet#313]
I've had this issue ever since I first Installed EarTrumpet, but never really bothered to make a ticket. When I want to adjust Tidal's volume it will work, but since Tidal has an inbuilt audio adjuster when pausing and resuming it will just reset the setting put in by EarTrumpet and go back to the value that is in the audio adjuster (Tidal's volume value in EarTrumpet switches to the one Tidal's audio adjuster is using once the music is resumed). While Spotify has an audio adjuster too, this issue doesn't occur with Spotify, I'm unsure if you're able to fix this on your end, but I thought I'd give it a shot because It's been bugging me for a while now.

**Comment by riverar** [comment]
Will take a look right now. Some apps do this (e.g. SoundCloud) and usually we just start an email chain with them and hope for the best.

**Comment by riverar** [comment]
Can't reproduce with Tidal `2.2.4.515 (W: 3.5.5--5) (NP: NA)` and EarTrumpet `2.0.7.0` on Windows 10 17763.

Does this look right?
![tidal](https://user-images.githubusercontent.com/475132/49842502-a323d880-fd70-11e8-88ab-7f5497e17559.gif)

**Comment by briank6932** [comment]
I'm on w10 1803 and Using the latest version of Tidal (2.2.4), with the latest version of EarTrumpet (2.0.7.0), however, you're reproducing the issue wrong. Once you adjust the volume on EarTrumpet, pause and resume the song you're listening to, once resumed the value will change back Tidal's inbuilt audio adjuster.

**Comment by briank6932** [comment]
It may be exclusive due to my HiFi account, I can share an obs video or something if you want, your client does look different than mine so it may actually be that. For example, we have different pause and play buttons and different audio adjustment locations and different actions at the bottom right-hand corner of the client.

**Comment by riverar** [comment]
Oh I was in the fullscreen experience. No difference with this UI either:
![image](https://user-images.githubusercontent.com/475132/49844486-14b35500-fd78-11e8-891a-e4b8c98f5147.png)

Maybe you're right, could be HiFi related? I suspect it's OS related though.

**Comment by briank6932** [comment]
I really doubt it has to do with Windows since we are running very similar builds, Will a video be of any help?

**Comment by briank6932** [comment]
Confirmed it's due to Hifi! I switched my streaming method and EarTrumpet adjustment works after pausing, on top of that the icon representing Tidal in EarTrumpet changes

**Comment by briank6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/49845021-f7d84b00-fd92-11e8-8581-2005c3d38f44.png)
Here's a picture of the change, the HiFi audio meter remains visible but does nothing

**Comment by riverar** [comment]
Interesting, thanks! I emailed the TIDAL team to get some help here. Will update you when I hear more.

**Comment by riverar** [comment]
Got a short-term paid account from TIDAL (thanks!) to debug this. Appears the child tidalplayer.exe process isn't reporting external volume changes back to the parent app. So when the parent app sends down the volume command again, it's wrong and clobbers your system settings.

Will email the team, should be an easy fix.

**Comment by briank6932** [comment]
Any update on this?

**Comment by riverar** [comment]
@briank6932 I emailed the TIDAL team December 14, not much else we can do at the moment.

**Comment by riverar** [comment]
@briank6932 Update: I emailed the TIDAL team again just now to request an update. I tested with latest TIDAL `2.3.0.530 (W: 3.6.3--3) (NP: NA)`, still has this issue.

**Comment by danhorntx** [comment]
I just started using Ear Trumpet in May of 2019 and I'm also having this issue. :(

**Comment by riverar** [comment]
@danhorntx Yep, we've emailed them about this. Please file an issue with TIDAL, feel free to reference this page as well as TIDAL issue numbers 655669 and 681745.

**Comment by danhorntx** [comment]
> 
> 
> @danhorntx Yep, we've emailed them about this. Please file an issue with TIDAL, feel free to reference this page as well as TIDAL issue numbers 655669 and 681745.

Doing that now. Sorry wasn't trying to beat up on you, thanks for what you've done so far!

**Comment by czif** [comment]
Hi, 
I have this issue. It's automatically changing volumes in Trumpet without my knowledge!

**Comment by riverar** [comment]
Sorry, no workaround. We've mailed TIDAL engineers multiple times. Can you please open a ticket with TIDAL and let them know this is an issue on their end? Reference my ticket 681745.

**Comment by Egglestron** [comment]
Hi. I just opened a new ticket, with a reference to yours. I'm trying to automate my app's volumes using Nirsoft's SoundVolumeView and some batch files, but I can't as the aforementioned issue is still plaguing TIDAL.

**Comment by LuisBessa22** [comment]
Hi. The best you can for now is: Settings > Streaming > Sound Output > More Settings > Use Exclusive Mode and Force Volume. You still need to increase volume after each song, but you can go to your normal volume instead of Ear Trumpet. But I really hope this get fixed, almost 2 years now.

**Comment by MasterPuffin** [comment]
It's 2021 now and still not fixed. I emailed the Tidal team again but got an half arsed reply, that they will look into it. Well I'm just gonna cancel my Tidal subscription in the meantime...

**Comment by Aidiiin** [comment]
Uncheck the Loudness Normalization setting in Tidal.

**Comment by brian6932** [comment]
@Aidiiin That doesn't fix the issue

**Comment by constroyer** [comment]
Any updates on this issue. I would hope it has been resolved by now

**Comment by MasterPuffin** [comment]
No just checked, even if loudness normalization is disabled the issue still occurs. Back to Spotify I guess...

**Comment by msu320** [comment]
this issue is not specific to Eartrumpet and happens even without it installed. TIDAL needs to fix this long standing issue.

**Comment by riverar** [comment]
This issue is pretty stale now and TIDAL remains broken, so closing for now.
