### ISSUE TITLE
EarTrumpet isn't starting on boot on Windows 10

### ISSUE THREAD

**Issue by dasme** [File-New-Project/EarTrumpet#468]
Since reinstalling Windows, EarTrumpet is no longer starting on boot. I'm unable to find any "Load on Boot" settings in the settings menu, and it isn't listed in the "Startup Apps" section of the windows settings panel.

This is for the Windows 10 Store version.

**Comment by Zcehtro** [comment]
Same problem with me.
After an update, it won't start automatically and I can't find any setting within the app that will make it start at logon.

**Comment by riverar** [comment]
What version/build of Windows 10 are you two using?

**Comment by dasme** [comment]
I'm running

Windows 10 Pro
Version 1909
Build 18363.657

**Comment by Yang-Richard** [comment]
Same problem here as well. 

Currently set to start on boot. The application is listed as a background process in task manager and the "start" screen shows up (cannot un-click data share), however the icon is not in the task bar and cannot access the EarTrumpet UI.

When I manually end task and start it again, the start screen pops up and then the same issue as above. Only this time, the task is not even in background processes. 

Windows 10 Education
Version 1909
Build 18363.720

**Comment by Zcehtro** [comment]
Now it's working like normal again.
I just turned on my computer and found EarTrumpet in the system tray, but I had to move it out from the hidden menu and next to the clock to have its icon always visible.
Most likely it was solved somehow.

Just in case, here's my data:
Windows 10 Pro
Version 1909
OS Build 18363.720

**Comment by Yang-Richard** [comment]
Unfortunately I can't share the same resolution, still seeing the same issue. Just tried rebooting, EarTrumpet is showing as a background process in Task Manager with EarTrumpet (32bit) and Runtime Broker sub-processes. 

Can't find the icon hidden away in the system tray, and Ear Trumpet does not appear as an option when going to the "select which icon appears on the taskbar" settings page in Taskbar Settings.

**Comment by riverar** [comment]
@Yang-Richard Does it show up in Task Manager > Startup tab?

**Comment by Yang-Richard** [comment]
Yes, listed with status enabled and startup impact not measured. 

> When I manually end task and start it again, the start screen pops up and then the same issue as above. Only this time, the task is not even in background processes.

Slight update to my previous post. I can now start and stop the background process, but still doesn't show up as visible or hidden in the task bar.

**Comment by dasme** [comment]
I have nothing EarTrumpet related in Task Manager > Startup. Just rebooted and no EarTrumpet task is currently running. It's not listed in Settings -> Startup -> Startup Apps either.

**Comment by riverar** [comment]
@dasme Strange, let me spin up an education image right now and see what's going on. Standby!

**Comment by riverar** [comment]
Are you using Windows 10 Pro *for workstations* by any chance? If you Start > Run > ms-settings:startupapps and click OK, what happens?

Can you also use regedit to check HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System and see if the following values exist?

SupportFullTrustStartupTasks
EnableFullTrustStartupTasks

Also, check HKCU\Software\Policies\Microsoft\Windows\Explorer for EnableAllStartupApplications.

**Comment by Yang-Richard** [comment]
Unclear if you're speaking to dasme or everyone, but I'm not on Win10Pro. Entering that in run just brings me to the settings startup apps page.

![image](https://user-images.githubusercontent.com/5545750/77037111-f2e74b80-6986-11ea-8220-1c72077b8d81.png)

I could not find _SupportFullTrustStartupTask_ or _EnableFullTrustStartupTasks_ in that directory as far as I can tell. This is what exists at that directory.

![image](https://user-images.githubusercontent.com/5545750/77037408-a7816d00-6987-11ea-82a8-10add666b68e.png)

I could not find _EnableAllStartupApplications_ at that final directory.

**Comment by riverar** [comment]
@Yang-Richard Can you save this as StartupTasks.reg, double-click it, merge it into the registry and reboot? Should resolve your issue.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

**Comment by riverar** [comment]
I'm also interested to hear if any of you are running third-party utilities that may have deleted the policies above. Are you using any sort of "de-bloating" or privacy-related tools for Windows 10? W10Privacy? Windows10Debloater? Any sort of telemetry blocking tools? Any registry cleaners or similar utilities?

**Comment by Zcehtro** [comment]
> I'm also interested to hear if any of you are running third-party utilities that may have deleted the policies above. Are you using any sort of "de-bloating" or privacy-related tools for Windows 10? W10Privacy? Windows10Debloater? Any sort of telemetry blocking tools? Any registry cleaners or similar utilities?
No. Once in a while I run CCleaner, but only for file cleanup. I don't touch anything in the registry.

> Was this a machine upgraded from a previous version of Windows (e.g. Windows 7 or 8)? OEM provided or clean/self-installed?
In my case, I set up my computer from scratch with Win10 Home in Spanish, then change the default system language to English-US.
Then set it up with en Education license.
Finally upgrade to a OEM Pro license.

Hope that info helps.

**Comment by dasme** [comment]
> Are you using Windows 10 Pro **For Workstations** by any chance? If you Start > Run > ms-settings:startupapps and click OK, what happens?
> 

Nope, just Windows 10 Pro. This is a fresh install that I did in December. Installed my GoXLR Mixer, OBS and other streaming apps and hardware. I installed EarTrumpet from the Windows Store. Images of my settings follow:

<img width="183" alt="version" src="https://user-images.githubusercontent.com/2388696/77121146-8ca30d00-6a08-11ea-8624-532c562249de.png">

<img width="372" alt="startup" src="https://user-images.githubusercontent.com/2388696/77121138-86ad2c00-6a08-11ea-92c6-a86da36bbc1f.png">

> Can you also use regedit to check HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System and see if the following values exist?
> 
> SupportFullTrustStartupTasks
> EnableFullTrustStartupTasks

Yep.

<img width="336" alt="regedit" src="https://user-images.githubusercontent.com/2388696/77121294-d8ee4d00-6a08-11ea-90dd-0c1f074ecf68.png">

> Also, check HKCU\Software\Policies\Microsoft\Windows\Explorer for EnableAllStartupApplications.

Hmm. I don't seem to have an Explorer entry.

<img width="576" alt="regedit2" src="https://user-images.githubusercontent.com/2388696/77121428-2c609b00-6a09-11ea-9a65-8efa424fca77.png">

**Comment by dasme** [comment]
> I'm also interested to hear if any of you are running third-party utilities that may have deleted the policies above. Are you using any sort of "de-bloating" or privacy-related tools for Windows 10? W10Privacy? Windows10Debloater? Any sort of telemetry blocking tools? Any registry cleaners or similar utilities?
> 
> Was this a machine upgraded from a previous version of Windows (e.g. Windows 7 or 8)? OEM provided or clean/self-installed?

Sorry forgot to add that I haven't run any cleaning utils or anything else on this machine that would touch the registry. Just did a clean install of Windows 10 from scratch.

**Comment by Yang-Richard** [comment]
@riverar Tried the solution you suggested, reporting back that it did not work. I did check to make sure the registry edits were made. No changes to how EarTrumpet is currently acting on boot. 

![image](https://user-images.githubusercontent.com/5545750/77499266-07fd2800-6e28-11ea-9e04-a9635af8c358.png)

No cleaners on my PC, only thing I could think of is Disk Cleanup or MalwareBytes. This is a fresh self-install from approximately 2 months ago.

One thing I did randomly stumble upon is that the program is underlined in the Start Menu, see below. Not sure if this is related, no other selection is like that. 

![image](https://user-images.githubusercontent.com/5545750/77499454-82c64300-6e28-11ea-902c-38de3babddab.png)

**Comment by riverar** [comment]
@Yang-Richard Interesting, that's a progress bar. It's as if it never fully finished installing? Can you try uninstalling/reinstalling now that the registry entries are in place? (right-click that tile in Start)

**Comment by Yang-Richard** [comment]
That's odd. I just uninstalled and attempted to reinstall through the Microsoft Store. Goes through the following actions
- Downloading EarTrumpet
- Restoring User Data
- Installing EarTrumpet
- Error (Code: 0x80073D05)

1. Is there an alternate location or .exe I can download from?
2. Perhaps there's still some config files somewhere. I couldn't find EarTrumpet in Program Files or appdata after uninstalling.

**Comment by riverar** [comment]
Sounds like something is latching onto `%LocalAppData%\Packages\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne`

**Comment by lisonge** [comment]
[win10x64 pro 2004] can not also find start-boot setting
but you can copy shortcut to C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
then the eartrumpet will start on boot

**Comment by riverar** [comment]
@lisonge Can you also perform the steps here? I would like to see your registry settings. https://github.com/File-New-Project/EarTrumpet/issues/468#issuecomment-601000004

**Comment by lisonge** [comment]
@riverar 
1. Start > Run > ms-settings:startupapps, item eartrumpet not exists, but if "C:\Users\lisonge\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup" has eartrumpet shortcut, item eartrumpet will exists
2.HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System has both values SupportFullTrustStartupTasks=(int32)1 and EnableFullTrustStartupTasks=(int32)2
3.my computer does not have item "computer\*\Software\Policies\Microsoft\Windows\Explorer"

**Comment by Yang-Richard** [comment]
Been a while but I just wanted to provide an update on my side since I still see this as open. 

Tried installing a couple months back and it seems to work now, running Windows 10 Education version 2004 (OS Build 19041.1052). If anyone is still troubleshooting or experiencing this bug, let me know and I can provide logs/info from a working PC.

**Comment by robinhood2014** [comment]
Some weird behavior I've noticed while experiencing the same issue:

1. When I open Task Manager and click the Startup tab, EarTrumpet shows as disabled. So I right-click and tell Task Manager to "Enable" that startup program, and it now shows as enabled.
2. BUT... When I open Task Manager again, and click the Startup tab, EarTrumpet is shown as disabled again.

Which means SOMETHING on my system is automatically setting that startup program to disable.

Taking a look at Process Explorer, I found something called "PowerLauncher.exe," a component of Microsoft PowerToys for Windows 10 (`https://www.github.com/Microsoft/PowerToys`) in the same process tree as EarTrumpet.exe. And so:

1. Thinking it was interfering with enabling the startup task, I disabled PowerToys Run.
2. I tried uninstalling all of PowerToys.
3. I also uninstalled CCleaner, which is known to cause havoc with a lot of stuff on lots of Windows computers.

None of these actions changed the behavior.

My next step will be to try a vanilla boot by way of msconfig.exe.

**Comment by riverar** [comment]
@robinhood2014 Can you screenshot the registry settings, like the others did above? This sounds a lot like those policies aren't set properly.

**Comment by robinhood2014** [comment]
I'm afraid not. As I was undergoing a myriad of other problems with my PC at the time, I simply decided to invoke the "Reset this PC" option, which (yes, I know) doesn't really do anything as far as diagnosing where the problem was coming from... but at least I finally got the stupid thing to work.

**Comment by riverar** [comment]
@robinhood2014 No problem, reach out again if you see it, _especially_ on Windows 11 when that's released.

**Comment by mkruselj** [comment]
Happens here on W10 Pro 22H2, too...

**Comment by mkruselj** [comment]
No response?

**Comment by riverar** [comment]
@mkruselj Hey there, this is sadly a Windows bug. Can you verify the registry settings listed above?

**Comment by mkruselj** [comment]
OK, I just checked. I did not have those registry keys at all under Policies\System, so I have added them. Rebooting to test...

**Comment by kebek** [comment]
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
> "EnableFullTrustStartupTasks"=dword:00000002
> "EnableUwpStartupTasks"=dword:00000002
> "SupportFullTrustStartupTasks"=dword:00000001
> "SupportUwpStartupTasks"=dword:00000001

I did this and fixed the issue, I'm on
Windows 10 Pro 
Version    22H2 
OSbuild   19045.2486

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. (This seems to be a popular Windows bug) Thanks!

**Comment by sebaschlax** [comment]
> @Yang-Richard Can you save this as `StartupTasks.reg`, double-click it, merge it into the registry and reboot? Should resolve your issue.
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
> "EnableFullTrustStartupTasks"=dword:00000002
> "EnableUwpStartupTasks"=dword:00000002
> "SupportFullTrustStartupTasks"=dword:00000001
> "SupportUwpStartupTasks"=dword:00000001
> ```

You are amazing bro, thx

**Comment by Bigdeath** [comment]
> @Yang-Richard Can you save this as `StartupTasks.reg`, double-click it, merge it into the registry and reboot? Should resolve your issue.
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
> "EnableFullTrustStartupTasks"=dword:00000002
> "EnableUwpStartupTasks"=dword:00000002
> "SupportFullTrustStartupTasks"=dword:00000001
> "SupportUwpStartupTasks"=dword:00000001
> ```

Helped me! Thx!

**Comment by Zaul13** [comment]
> @Yang-Richard Can you save this as `StartupTasks.reg`, double-click it, merge it into the registry and reboot? Should resolve your issue.
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
> "EnableFullTrustStartupTasks"=dword:00000002
> "EnableUwpStartupTasks"=dword:00000002
> "SupportFullTrustStartupTasks"=dword:00000001
> "SupportUwpStartupTasks"=dword:00000001
> ```

Thanks my guy, you a life saver for just telling to just make a txt document and after copying all of that inside in the file change the whole document (including file format) to just StartupTasks.reg, open it and restarting [btw im being genuine the thing is i was a dumbass and took me 20min to understand thats what i had to do, so im saying it for other dumbasses like me lol, but srs thx a lot <3]

**Comment by riverar** [comment]
@Zaul13 Can you help me identify how this happened? Did you use a debloater script or something similar?

**Comment by riverar** [comment]
@Zaul13 which debloater script?

**Comment by Zaul13** [comment]
@riverar i did it about half a year ago so I dont remember exactly but I THINK it was this one from this yt tutorial
[https://www.youtube.com/watch?v=7SdtxrsZN8k](https://www.youtube.com/watch?v=7SdtxrsZN8k)
