### ISSUE TITLE
EarTrumpet uses the dedicated gpu instead of the integrated

### ISSUE THREAD

**Issue by qwewer0** [File-New-Project/EarTrumpet#771]
## Description
EarTrumpet uses the dedicated (nvidia gtx 1060) gpu instead of the integrated (intel hd 630)

Changed the used gpu to the integrated in the nvidia control panel and in the windows graphics settings.

## Steps to reproduce
1. Start EarTrumpet
2. See that it is using the dedicated gpu

## Meta
* EarTrumpet.Package_2.1.8.173_x86
* Version	10.0.19042 Build 19042

## Screenshots
![bandicam 2021-02-27 13-43-18-749](https://user-images.githubusercontent.com/57561110/109387453-d4f9c900-7901-11eb-8983-6a5bb4a85357.jpg)

**Comment by riverar** [comment]
Isn't really an EarTrumpet bug per se. Will leave this open while we investigate whether or not there's an API for us to pick GPU affinity. Otherwise you'll probably have to rely on the GPU vendor software to make those choices.

**Comment by ArsenicBismuth** [comment]
Definitely EarTrumpet problem since forcing it using both control panel & windows built-in setting doesn't work. I have no problem with other apps unless they have in-app GPU selector.

**Comment by riverar** [comment]
I'm personally having this problem now too, ha!

**Comment by 1aTa** [comment]
EarTrumpet is the only app I use which blocks nVidia Advanced Optimus from switching from "Auto Select" to "dGPU only" display mode when a game launches.

I have to close EarTrumpet and then relaunch after the game closes.

**Comment by shazlee00** [comment]
@1aTa  have got the same issue don't know what causes it or how to fix it

**Comment by riverar** [comment]
Should be fixed in dev as of https://github.com/File-New-Project/EarTrumpet/commit/39f2553959aa84d9dc098870c052c8346d25ad7e. Seems to be leaving my GPU alone now. Give it a try and let me know!

**Comment by AudreyAP** [comment]
I am still getting this on latest eartrumpet (installed from microsoft store). I'm not sure which commit this version is...

![image](https://github.com/File-New-Project/EarTrumpet/assets/130399040/d2e91be1-7576-47b3-a622-f75c67d4363a)

**Comment by AudreyAP** [comment]
![image](https://github.com/File-New-Project/EarTrumpet/assets/130399040/3c00c50f-3218-4792-8aa0-3c60ed7cfb20)
