### ISSUE TITLE
EarTrumpet show out of screen

### ISSUE THREAD

**Issue by maximecharriere** [File-New-Project/EarTrumpet#888]
## Description
The widget is placed too far to the right and therefore only a small part is visible (see screenshot), and the other part is not visible on the second screen.  

The widget returns to normal if I restart EarTrumpet.  

It goes back outside the screen when I plug in the docking station and stays outside even if I unplug the docking.   
Every time I plug-in/unplug the docking (every day in my case), EarTrumpet goes further and further away from the screen.  

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19043.1110
* Using 3 screens with Dell docking station, connected to the laptop via USB C.  

## Screenshots
![image](https://user-images.githubusercontent.com/51918753/128067313-4c325446-fafb-489b-9cea-2e17e7ea8bb0.png)

**Comment by riverar** [comment]
Dupe of #865, already fixed in dev builds.

@maximecharriere if you'd like, you can install a dev build directly from https://eartrumpet.app (link at the bottom).

**Comment by maximecharriere** [comment]
I have installed EarTrumpet(dev) 2.1.8.187 but I still have this issue. 

https://user-images.githubusercontent.com/51918753/128073012-0b52f114-d6ad-44b4-ba94-1a6db479d5f4.mp4

## Situation

- Laptop with 1 screen
- Docking with 3 screens

## How to reproduce

1. Start EarTrumpet -> All good
2. Disconnect from docking -> All good
3. Reconnect to the docking -> EarTrumpet go ~20% to the right (impossible to see the numbers)
4. Disconnect from docking -> EarTrumpet stays too far to the right
5. Reconnect to the docking -> Another 20% too far to the right (40% in total)
6. Restart EarTrumpet -> All good

**Comment by riverar** [comment]
@maximecharriere Dang, will take another look. Awesome video, thanks!

**Comment by jesstech** [comment]
Probably related to #768 as well

**Comment by raulvasquez** [comment]
I am also experiencing the same behavior on my setup when docking / undocking my laptop

**Comment by thrik** [comment]
Hi, this is still happening for me. Commenting bc I saw this was to be fixed a year ago. I am using a 4k monitor so I'm not sure if that's adding to this.

![image](https://user-images.githubusercontent.com/326814/161906717-5dd222dd-7bda-41a0-944a-017a14e312d4.png)

**Comment by riverar** [comment]
@thrik Can you share your version number?

**Comment by thrik** [comment]
2.1.10.0

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue 1304, thanks!

**Comment by PP100** [comment]
I still have this problem with the general release version for months . I'm not clear when this was closed and tied to another "master issue " if it was supposed to  have been fixed by now . I just tried the dev 20,3.20 version and still have the issue whereby it starts correct but after a short time, cuts off the fly out on the right edge of the screen. I am on Windows 10  22H2 os build 19045.4291.
If I stop it running Ear trumpet then restart  it it corrects  it temporarily  then it  it comes back.
Am often running Windows on  2 screens - extending display.
![Untitled mp4_snapshot_00 03 353](https://github.com/File-New-Project/EarTrumpet/assets/40966576/3e08b0fc-c437-4520-86ea-f3e3f1bfbb80)
